### ISSUE TITLE
Add RefGet support

### ISSUE THREAD

**Issue by jdidion** [refgenie/refgenie#79]
[RefGet](http://samtools.github.io/hts-specs/refget.html) is a GA4GH standard for retrieving reference genomes by name or checksum. It seems natural for RefGenie to support this protocol given that it can serve fasta references.

**Comment by nsheff** [comment]
Thanks for the feedback, we're thinking the same thing! I was [thinking about](https://github.com/databio/refgenconf/issues/25) adding refget checksums as an attribute for the genomes.

There are two issues at the moment: First,  the refget protocol is currently concerned with individual sequences rather than collections, but this is apparently on the docket for refget v2.  The other thing is... by my understanding of the refget protocol, you can retrieve sequences themselves given a checksum, but actually *not* by name (which will be hard to do because of non-congruence of names...). So, our use case is again slightly different than the current protocol. I am in communication with @andrewyatz about how we can link the ideas of refgenie and refget. I'm really hopeful that we'll be able to link these two projects together, which I think will go a long way toward standardizing genome sequences and accompanying assets. But we're kind of just starting to image the best path forward.

**Comment by andrewyatz** [comment]
Hi. To give some background here. The aim of refget will always be retrieval by checksum as it’s one of the few ways we’ve found to make a totally unambiguous call. 

What we are looking at supporting though is sequence collections (the concept of a genome or transcriptome or proteome) and checksum discovery using other known identifiers or aliases. My hope is both of these new protocols will eventually boil down to “and here are the checksums”. 

I can imagine others building far more complex protocols and utilities on top of this but these feel like the building blocks we need.

**Comment by nsheff** [comment]
Thanks @andrewyatz 

I think refgenie will be able to easily build on top of refget to add in the capability of retrieving things by name, which I'm starting to brainstorm about in #81. Because of the 'config file' approach of refgenie this seems to fit naturally here, so I think it's a great complement to refget.

I have also started brainstorming a few ideas about the collection-level checksums in #82. I will be interested in hearing more about your approach to that.

**Comment by nsheff** [comment]
I've implemented basic 'getseq' support now in this commit: ea877584e8ad91eab369343466d2ca5248dd51ca.

it works like this on dev:

```
refgenie getseq -g hg38 -l chr1:50000-50200
AAACAGGTTAATCGCCACGACATAGTAGTATTTAGAGTTACTAGTAAGCCTGATGCCACTACACAATTCTAGCTTTTCTCTTTAGGATGATTGTTTCATTCAGTCTTATCTCTTTTAGAAAACATAGGAAAAAATTATTTAATAATAAAATTTAATTGGCAAAATGAAGGTATGGCTTATAAGAGTGTTTTCCTATTGTT
```

at the moment it is not yet using the refget/hashing...it just uses the refgenie local human-readable identifier for genome.

**Comment by nsheff** [comment]
@jdidion maybe of interest: I've spun off refget functionality into a separate python package called [refget](http://refget.databio.org/en/latest/) -- we're now working to incorporate this into refgenie for sequence identifiers.
